$("#team1w").text("1 Gonzaga");
$("#team2w").text("2 Duke");
$("#team3w").text("3 Texas Tech");
$("#team4w").text("4 Arkansas");
$("#team5w").text("5 Connecticut");
$("#team6w").text("6 Alabama");
$("#team7w").text("7 Michigan St.");
$("#team8w").text("8 Boise St.");
$("#team9w").text("9 Memphis");
$("#team10w").text("10 Davidson");
$("#team11w").text("11 Notre Dame");
$("#team12w").text("12 New Mexico St.");
$("#team13w").text("13 Vermont");
$("#team14w").text("14 Montana St.");
$("#team15w").text("15 CSU Fullerton");
$("#team16w").text("16 Georgia St.");

$("#team1s").text("1 Arizona");
$("#team2s").text("2 Villanova");
$("#team3s").text("3 Tennessee");
$("#team4s").text("4 Illinois");
$("#team5s").text("5 Houston");
$("#team6s").text("6 Colorado St.");
$("#team7s").text("7 Ohio St.");
$("#team8s").text("8 Seton Hall");
$("#team9s").text("9 TCU");
$("#team10s").text("10 Loyola Chicago");
$("#team11s").text("11 Michigan");
$("#team12s").text("12 UAB");
$("#team13s").text("13 Chattanooga");
$("#team14s").text("14 Longwood");
$("#team15s").text("15 Delaware");
$("#team16s").text("16 Wright State");

$("#team1e").text("1 Baylor");
$("#team2e").text("2 Kentucky");
$("#team3e").text("3 Purdue");
$("#team4e").text("4 UCLA");
$("#team5e").text("5 St. Mary's");
$("#team6e").text("6 Texas");
$("#team7e").text("7 Murray St.");
$("#team8e").text("8 North Carolina");
$("#team9e").text("9 Marquette");
$("#team10e").text("10 San Francisco");
$("#team11e").text("11 Virginia Tech");
$("#team12e").text("12 Indiana");
$("#team13e").text("13 Akron");
$("#team14e").text("14 Yale");
$("#team15e").text("15 St. Peter's");
$("#team16e").text("16 Norfolk St.");

$("#team1m").text("1 Kansas");
$("#team2m").text("2 Auburn");
$("#team3m").text("3 Wisconsin");
$("#team4m").text("4 Providence");
$("#team5m").text("5 Iowa");
$("#team6m").text("6 LSU");
$("#team7m").text("7 USC");
$("#team8m").text("8 SDSU");
$("#team9m").text("9 Creighton");
$("#team10m").text("10 Miami");
$("#team11m").text("11 Iowa St.");
$("#team12m").text("12 Richmond");
$("#team13m").text("13 South Dakota St.");
$("#team14m").text("14 Colgate");
$("#team15m").text("15 Jacksonville St.");
$("#team16m").text("16 Texas Southern");